ws4_parameters:
  kappa: 1.139  # WS4 surface asymmetry coefficient
  xi: 1.250     # WS4 isospin coefficient
  fs: 1.0       # Scaling factor
baseline_params:
  model_type: "ws4"  # Can easily be swapped to "none" or "ws4" in the future
  ws4_coeffs:
    a_v: 15.5906
    a_s: 17.0251
    a_c: 0.7053
    kappa: 1.139
    delta_0: 11.2
  ldm_coeffs:
    a_v: 15.75
    a_s: 17.8
    a_c: 0.711
    a_a: 23.7
    delta_0: 11.18

zeng_2022_training:
  target_col: "binding_energy_total_mev"
  learning_rate: 0.0001
  beta1: 0.9
  beta2: 0.999
  epochs: 30000
  batch_size: 64
  scaler_type: "standard"
  test_set_definition: "promoted"
  scale_target: true
  lr_schedule: "constant"
  weight_decay: 1.0e-4
  smoke_run: false  # Override epochs to 5 for rapid testing
  model_suite:
    # ANN2:
    #   features: ["z", "n"]
    #   hidden_dims: [35, 19]
    # ANN4:
    #   features: ["z", "n", "z_eo", "n_eo"]
    #   hidden_dims: [35, 17]
    # ANN6:
    #   features: ["z", "n", "z_eo", "n_eo", "delta_z", "delta_n"]
    #   hidden_dims: [32, 17]
    ANN7:
      features: ["z", "n", "z_eo", "n_eo", "delta_z", "delta_n", "asy"]
      hidden_dims: [32, 16]
